"""
async_scheduler.py — Asynchronous FPGA Pipeline Scheduler
==========================================================
Implements two background threads that form Stage 2 of the pipeline:

  Thread 1 — fpga_async_worker
      Dequeues a buffer index from fpga_task_queue, drives the FPGA kernel
      (AXI-Lite AP_START), then enqueues the index to fpga_done_queue.

  Thread 2 — interrupt_worker  /  real_interrupt_worker
      Waits for the FPGA completion interrupt (AP_DONE IRQ), invalidates
      the CPU cache for the output buffer (DDR → Cache sync), then
      forwards the buffer index to cpu_post_queue so Stage 1 can
      post-process the result.

Queue data flow
---------------
  fpga_task_queue  →  fpga_async_worker  →  fpga_done_queue
                                                 ↓
                                        interrupt_worker
                                                 ↓
                                         cpu_post_queue  →  Stage 1

Deployment note
---------------
Call init_kv260_scheduler(overlay) before starting the threads to bind
the FPGA IP and interrupt objects from the loaded overlay.
"""

import threading
import time
import queue

import ping_pong_buffer as ppb   # always access buffers via the module to
                                  # keep references valid after init calls

# ── Inter-stage queues ────────────────────────────────────────────────────────
fpga_task_queue: queue.Queue = queue.Queue()  # Stage 1 → Thread 1
fpga_done_queue: queue.Queue = queue.Queue()  # Thread 1 → Thread 2
cpu_post_queue:  queue.Queue = queue.Queue()  # Thread 2 → Stage 1

# ── KV260 hardware objects (populated by init_kv260_scheduler) ────────────────
_fpga_ip      = None   # overlay.mmult_accel_0
_my_interrupt = None   # overlay.mmult_accel_0.interrupt


# ── Hardware initialisation ───────────────────────────────────────────────────

def init_kv260_scheduler(overlay) -> None:
    """
    Bind the FPGA IP core and interrupt object from a loaded PYNQ overlay.
    Must be called before build_scheduler_threads(sim=False).

    Parameters
    ----------
    overlay : pynq.Overlay
        A fully loaded overlay (bitstream already programmed into the PL).
    """
    global _fpga_ip, _my_interrupt
    _fpga_ip      = overlay.mmult_accel_0
    _my_interrupt = overlay.mmult_accel_0.interrupt


# ── FPGA kernel wrappers ──────────────────────────────────────────────────────

def _sim_fpga_kernel(buf_idx: int) -> None:
    """
    Simulation-only: mimics a 0.5 s FPGA matrix-multiply computation.
    Reads from ppb.input_buffers and writes a string result to
    ppb.output_buffers so that Stage 1 post-processing has something to read.
    """
    in_data = ppb.input_buffers[buf_idx]
    time.sleep(0.5)   # emulate FPGA compute latency
    ppb.output_buffers[buf_idx] = f"[H/W result for '{in_data}']"


def _real_fpga_kernel(buf_idx: int) -> None:
    """
    KV260 hardware path: flush CPU cache to DDR, write AXI-Lite registers
    to supply buffer addresses, then assert AP_START to launch the HLS IP.

    AXI-Lite register map (generated by Vitis HLS):
        0x00 — Control (bit 0 = AP_START)
        0x10 — input_buffer  physical address (lower 32 bits)
        0x1C — output_buffer physical address (lower 32 bits)
    """
    ppb.input_buffers[buf_idx].flush()   # writeback CPU cache → DDR

    _fpga_ip.write(0x10, int(ppb.input_buffers[buf_idx].physical_address))
    _fpga_ip.write(0x1C, int(ppb.output_buffers[buf_idx].physical_address))
    _fpga_ip.write(0x00, 0x01)           # assert AP_START


# ── Thread 1: FPGA async worker ───────────────────────────────────────────────

def fpga_async_worker(sim: bool = False) -> None:
    """
    Stage 2 worker thread: consume buffer indices from fpga_task_queue,
    dispatch each to the FPGA kernel, then signal completion.

    A sentinel value of None in fpga_task_queue causes the thread to exit.

    Parameters
    ----------
    sim : bool
        True  → use _sim_fpga_kernel (software simulation).
        False → use _real_fpga_kernel (KV260 hardware).
    """
    kernel = _sim_fpga_kernel if sim else _real_fpga_kernel

    while True:
        buf_idx = fpga_task_queue.get()

        if buf_idx is None:              # shutdown sentinel
            fpga_task_queue.task_done()
            break

        kernel(buf_idx)

        fpga_done_queue.put(buf_idx)     # notify interrupt handler
        fpga_task_queue.task_done()


# ── Thread 2a: Simulation interrupt handler ───────────────────────────────────

def interrupt_worker() -> None:
    """
    Simulation interrupt handler: forwards completed buffer indices from
    fpga_done_queue directly to cpu_post_queue without waiting for a real IRQ.

    A sentinel value of None causes the thread to exit.
    """
    while True:
        buf_idx = fpga_done_queue.get()

        if buf_idx is None:              # shutdown sentinel
            fpga_done_queue.task_done()
            break

        cpu_post_queue.put(buf_idx)
        fpga_done_queue.task_done()


# ── Thread 2b: KV260 real interrupt handler ───────────────────────────────────

def real_interrupt_worker() -> None:
    """
    KV260 hardware interrupt handler.

    Sequence per buffer:
      1. Block on _my_interrupt.wait()      — ARM waits for AP_DONE IRQ.
      2. _my_interrupt.clear()              — acknowledge / deassert IRQ line.
      3. output_buffers[buf_idx].invalidate()— flush DDR contents into CPU cache
                                              so that Stage 1 reads fresh data.
      4. Enqueue buf_idx to cpu_post_queue  — hand off to Stage 1 post-process.

    A sentinel value of None causes the thread to exit.
    """
    while True:
        buf_idx = fpga_done_queue.get()

        if buf_idx is None:              # shutdown sentinel
            fpga_done_queue.task_done()
            break

        _my_interrupt.wait()                          # block on AP_DONE IRQ
        _my_interrupt.clear()                         # clear interrupt flag
        ppb.output_buffers[buf_idx].invalidate()      # DDR → CPU cache sync

        cpu_post_queue.put(buf_idx)
        fpga_done_queue.task_done()


# ── Thread factory ─────────────────────────────────────────────────────────────

def build_scheduler_threads(sim: bool = False):
    """
    Create (but do not start) the two Stage-2 threads.

    Returns
    -------
    (t_fpga, t_irq) : tuple[threading.Thread, threading.Thread]
    """
    t_fpga = threading.Thread(
        target=fpga_async_worker,
        kwargs={"sim": sim},
        daemon=True,
        name="fpga-async-worker",
    )
    irq_target = interrupt_worker if sim else real_interrupt_worker
    t_irq = threading.Thread(
        target=irq_target,
        daemon=True,
        name="irq-handler",
    )
    return t_fpga, t_irq


def reset_queues() -> None:
    """
    Drain all inter-stage queues. Call between test runs to avoid
    leftover state from a previous pipeline execution.
    """
    for q in (fpga_task_queue, fpga_done_queue, cpu_post_queue):
        while not q.empty():
            try:
                q.get_nowait()
                q.task_done()
            except queue.Empty:
                break
